### ISSUE TITLE
Add missing jQuery libraries

### ISSUE THREAD

**Issue by gteufelberger** [ollie-sara/roominfo_checker#1]
Concerning the used but not pushed jQuery libraries I just checked their licensing and the following are released under [MIT License](https://en.wikipedia.org/wiki/MIT_License):

- [jQuery 3.6.0](https://jquery.org/license/)
- [jQuery UI Touch-Punch](https://www.npmjs.com/package/jquery-ui-touch-punch (`Ctrl`+`F` -> "MIT"))
- [jQuery DataTables 1.11.3](https://datatables.net/faqs/index#Licensing)

while [jQuery UI](https://github.com/jquery/jquery-ui/blob/main/LICENSE.txt) is [CC0](http://creativecommons.org/publicdomain/zero/1.0/) and as such public domain and free to use.

So by simply releasing your code under the MIT license by adding the appropriate `LICENSE` file you can freely add the jQuery source files to the repo \^\^

**Comment by ollie-sara** [comment]
Thanks for doing what I was too lazy to do :) The libraries are up now.
